"use client";

import { FormEvent, useState } from "react";
import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { approveAnalysisContext, createAnalysisContext, executeAnalysis, getAnalysis, runAnalysisQualityGate } from "@/lib/api";
import type { AnalysisExecution, QuerySpec } from "@/lib/analysis-types";
import { ErrorNotice, LoadingBlock, Notice, PageHeader, StatusBadge } from "@/components/ui";

const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

export default function AnalysisWorkspacePage() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const session = useQuery({ queryKey: ["analysis", sessionId], queryFn: ({ signal }) => getAnalysis(sessionId, signal), enabled: Boolean(sessionId) });
  const [rowGrain, setRowGrain] = useState(""); const [dimensions, setDimensions] = useState(""); const [measures, setMeasures] = useState(""); const [column, setColumn] = useState(""); const [aggregate, setAggregate] = useState<QuerySpec["aggregate"]>("count"); const [groupBy, setGroupBy] = useState(""); const [execution, setExecution] = useState<AnalysisExecution | null>(null); const [error, setError] = useState<Error | null>(null); const [busy, setBusy] = useState(false);
  if (session.isLoading) return <LoadingBlock label="Đang mở analysis workspace…" />;
  if (session.isError || !session.data) return <ErrorNotice error={session.error || new Error("Không tìm thấy session.")} retry={() => session.refetch()} />;
  const data = session.data; const context = data.context;
  async function saveContext(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const saved = await createAnalysisContext(sessionId, { row_grain: rowGrain, keys: [], dimensions: split(dimensions), measures: split(measures), ignored_columns: [], limitations: [] }); await approveAnalysisContext(sessionId, saved!.id, "Analyst"); await runAnalysisQualityGate(sessionId); await session.refetch(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Không thể lưu context.")); } finally { setBusy(false); } }
  async function run(event: FormEvent) { event.preventDefault(); if (!context) return; setBusy(true); setError(null); try { setExecution(await executeAnalysis(sessionId, context.id, { aggregate, column: column || undefined, dimensions: split(groupBy), filters: [], limit: 100 })); await session.refetch(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Không thể chạy analysis.")); } finally { setBusy(false); } }
  return <><PageHeader eyebrow={`Analysis session · ${data.id}`} title={data.goal} description="Evidence-first workspace: context → quality → deterministic result." action={<StatusBadge status={data.status} />} />
    {error && <ErrorNotice error={error} />}
    <div className="grid two"><section className="panel"><div className="panel-title"><h2>1. Context</h2><small>{context?.status || "needs approval"}</small></div>{!context || context.status !== "approved" ? <form className="form-stack" onSubmit={saveContext}><label>Row grain<input value={rowGrain} onChange={(event) => setRowGrain(event.target.value)} placeholder="Một dòng đại diện cho…" /></label><label>Dimensions (comma separated)<input value={dimensions} onChange={(event) => setDimensions(event.target.value)} placeholder="city, status" /></label><label>Measures (comma separated)<input value={measures} onChange={(event) => setMeasures(event.target.value)} placeholder="salary, revenue" /></label><button className="button primary" disabled={busy}>Approve context & run quality gate</button></form> : <dl className="key-value"><dt>Grain</dt><dd>{context.context.row_grain || "Not specified"}</dd><dt>Dimensions</dt><dd>{context.context.dimensions.join(", ") || "—"}</dd><dt>Measures</dt><dd>{context.context.measures.join(", ") || "—"}</dd></dl>}</section>
      <section className="panel"><div className="panel-title"><h2>2. Quality gate</h2><small>{data.quality_gate?.decision || "not run"}</small></div>{data.quality_gate ? data.quality_gate.issues.length ? <ul className="warning-list">{data.quality_gate.issues.map((issue) => <li key={issue.id}><b>{issue.severity}</b> — {issue.message}</li>)}</ul> : <Notice tone="success">Không phát hiện quality issue cho context hiện tại.</Notice> : <p className="muted">Approve context để kiểm tra scope, sampling và metric readiness.</p>}</section></div>
    <section className="panel" style={{ marginTop: 18 }}><div className="panel-title"><h2>3. Explore</h2><small>Bounded aggregate; không chạy SQL/raw row.</small></div>{context?.status === "approved" && data.quality_gate?.decision !== "blocked" ? <form className="inline-actions" onSubmit={run}><label>Aggregate<select value={aggregate} onChange={(event) => setAggregate(event.target.value as QuerySpec["aggregate"])}><option value="count">Count rows</option><option value="count_distinct">Count distinct</option><option value="sum">Sum</option><option value="mean">Mean</option><option value="median">Median</option></select></label><label>Measure column<input value={column} onChange={(event) => setColumn(event.target.value)} placeholder="Required except count" /></label><label>Group by<input value={groupBy} onChange={(event) => setGroupBy(event.target.value)} placeholder="city" /></label><button className="button primary" disabled={busy}>Run</button></form> : <p className="muted">Hoàn tất context và quality gate để chạy phép tính.</p>}
      {execution && <div className="table-wrap" style={{ marginTop: 16 }}><table><thead><tr>{execution.result.columns.map((name) => <th key={name}>{name}</th>)}</tr></thead><tbody>{execution.result.data.map((row, index) => <tr key={index}>{execution.result.columns.map((name) => <td key={name}>{String(row[name] ?? "—")}</td>)}</tr>)}</tbody></table><p className="muted">Evidence {execution.id} · hash {execution.result_hash.slice(0, 12)} · {execution.duration_ms}ms</p></div>}</section>
  </>;
}
