import { mkdir, writeFile } from 'node:fs/promises';
import { z } from 'zod';
import {
  AnalysisRequestSchema,
  AnalysisPackSchema,
  AgentActivityEventV1Schema,
  AgentPlanV1Schema,
  AgentTurnRequestSchema,
  AgentTurnStreamEventV1Schema,
  AgentWorkflowStatusSchema,
  AvailableWorkspaceActionV1Schema,
  ArtifactSchema,
  CapabilityResultV1Schema,
  CanonicalAgentObservationV1Schema,
  ChartPackSchema,
  ComparisonPackSchema,
  ContextResolutionIssueV1Schema,
  CoordinatorDecisionSchema,
  DataAnalysisPackSchema,
  DecisionIntelligencePackSchema,
  DecisionIntelligenceResponseSchema,
  GroundedResponseSelectionV1Schema,
  InsightPackSchema,
  ReportDraftSchema,
  ReportDefinitionSchema,
  ReviewResultSchema,
  RunSchema,
  SnapshotRowSchema,
  WorkspaceActionV1Schema,
  WorkspaceContextV1Schema,
} from './index';
await mkdir('src/backend/packages/contracts/schema', { recursive: true });
for (const [name, schema] of Object.entries({
  AnalysisRequest: AnalysisRequestSchema,
  AnalysisPack: AnalysisPackSchema,
  AgentActivityEventV1: AgentActivityEventV1Schema,
  AgentPlanV1: AgentPlanV1Schema,
  AgentTurnRequest: AgentTurnRequestSchema,
  AgentTurnStreamEventV1: AgentTurnStreamEventV1Schema,
  AgentWorkflowStatus: AgentWorkflowStatusSchema,
  AvailableWorkspaceActionV1: AvailableWorkspaceActionV1Schema,
  Artifact: ArtifactSchema,
  CapabilityResultV1: CapabilityResultV1Schema,
  CanonicalAgentObservationV1: CanonicalAgentObservationV1Schema,
  ChartPack: ChartPackSchema,
  ComparisonPack: ComparisonPackSchema,
  ContextResolutionIssueV1: ContextResolutionIssueV1Schema,
  CoordinatorDecision: CoordinatorDecisionSchema,
  DataAnalysisPack: DataAnalysisPackSchema,
  DecisionIntelligencePack: DecisionIntelligencePackSchema,
  DecisionIntelligenceResponse: DecisionIntelligenceResponseSchema,
  GroundedResponseSelectionV1: GroundedResponseSelectionV1Schema,
  InsightPack: InsightPackSchema,
  ReportDraft: ReportDraftSchema,
  ReportDefinition: ReportDefinitionSchema,
  ReviewResult: ReviewResultSchema,
  Run: RunSchema,
  SnapshotRow: SnapshotRowSchema,
  WorkspaceActionV1: WorkspaceActionV1Schema,
  WorkspaceContextV1: WorkspaceContextV1Schema,
})) {
  await writeFile(
    `src/backend/packages/contracts/schema/${name}.json`,
    `${JSON.stringify(z.toJSONSchema(schema, { unrepresentable: 'any' }), null, 2)}\n`,
  );
}
