import Link from "next/link";
import { PublicFooter } from "@/components/public-footer";
import { PublicNavbar } from "@/components/public-navbar";

export const metadata = { title: "Giới thiệu · VDaAgent" };

const capabilities = [
  ["Dataset & nguồn dữ liệu", "Tải CSV, TSV, Parquet hoặc JSON; kết nối MongoDB Atlas qua datasource đã kiểm tra. Khi Workspace dùng Google Drive làm storage provider, nút OAuth kết nối xuất hiện trước khi upload và file được lưu ở Drive."],
  ["Profiling", "Profile Run tính schema, kiểu dữ liệu, số dòng/cột, null rate, cardinality, uniqueness, top values, thống kê mô tả, outlier, duplicate rows, correlation và cảnh báo chất lượng."],
  ["Review proposal", "Candidate key, semantic type và PII là các proposal có thể cần Analyst xác nhận. Chọn xác nhận, từ chối hoặc chỉnh sửa (kèm lý do khi chỉnh sửa) trước khi pipeline tiếp tục."],
  ["Command Center", "Đặt câu hỏi phân tích, tạo plan, chạy Preview bounded, xem visualization và Promote thành Official Evidence sau khi kiểm tra kết quả và limitations."],
  ["Insight Agent", "Hỏi đáp trong phạm vi Profile Run đã chọn. Agent diễn giải evidence được cấp; engine deterministic mới là nơi tính số liệu, không phải LLM."],
  ["Compare", "Chọn hai Profile Run đã completed làm Baseline và Current để xem aggregate signal về thay đổi phân phối, chất lượng hoặc cấu trúc; kết quả hiển thị severity theo cột."],
  ["Report", "Ghim Official Evidence hoặc reviewed insight vào Report Draft, sắp xếp và thêm ghi chú, tạo Snapshot bất biến, xem Preview và xuất PDF. Draft là bản chỉnh sửa; Snapshot là phiên bản cố định để chia sẻ và export."],
  ["Workspace & audit", "Dataset, Profile Run, evidence, report và hoạt động được scope theo Workspace. Thành viên, invitation và quyền truy cập được backend kiểm tra."],
];

export default function AboutPage() {
  return <div className="public-page"><PublicNavbar /><main className="pub-content"><section className="pub-section pub-page-hero"><div className="pub-container"><span className="pub-eyebrow">ABOUT / PRODUCT TRUTH</span><h1>VDaAgent biến profiling<br /><em>thành nền tảng phân tích.</em></h1><p className="pub-lead">Đây là workspace dành cho Analyst muốn biết dữ liệu có gì, kết quả đến từ đâu và insight được hỗ trợ bởi bằng chứng nào.</p><div className="pub-inline-actions"><Link href="/guide" className="pub-btn pub-btn-primary">Xem workflow →</Link><Link href="/docs" className="pub-btn pub-btn-secondary">Mở Documentation</Link></div></div></section>
    <section className="pub-section bg-surface" id="capabilities"><div className="pub-container"><div className="pub-section-header"><span className="pub-eyebrow">CAPABILITIES</span><h2>Một workspace,<br /><em>nhiều lớp kiểm chứng.</em></h2><p>Các nhóm dưới đây phản ánh những gì sản phẩm hiện hỗ trợ.</p></div><div className="pub-capability-grid">{capabilities.map(([title, body], index) => <article className="pub-capability-card" key={title}><span className="pub-card-index">{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="pub-section" id="architecture"><div className="pub-container"><div className="pub-section-header"><span className="pub-eyebrow">ARCHITECTURE</span><h2>Luồng kỹ thuật<br /><em>theo từng lớp.</em></h2><p>Frontend gọi API; API xác thực Workspace và điều phối engine, worker, persistence và LLM ở đúng ranh giới.</p></div><div className="pub-architecture-flow"><div><b>Frontend</b><small>Next.js · React · TypeScript</small></div><i aria-hidden="true">→</i><div><b>API</b><small>FastAPI · Pydantic · SQLAlchemy</small></div><i aria-hidden="true">→</i><div><b>Compute / worker</b><small>Profiling worker · DuckDB · pandas · NumPy · SciPy · statsmodels · scikit-learn</small></div><i aria-hidden="true">→</i><div><b>Persistence</b><small>PostgreSQL / Supabase · Storage</small></div></div><div className="pub-architecture-note"><b>LLM layer, khi phù hợp</b><p>LangGraph / LangChain hỗ trợ planner và Agent runtime. Chỉ metadata đã được giới hạn được đưa vào lớp này; không có arbitrary code, raw-row explorer hay arbitrary SQL trong UI.</p></div></div></section>
    <section className="pub-section bg-surface" id="principles"><div className="pub-container"><div className="pub-section-header"><span className="pub-eyebrow">DESIGN PRINCIPLES</span><h2>Vì sao workflow<br /><em>được tách lớp?</em></h2></div><div className="pub-principles-grid pub-principles-large"><article><b>Deterministic compute ≠ LLM</b><p>Engine thực hiện metric và phân tích bounded. LLM hỗ trợ lập kế hoạch, diễn giải và hỏi đáp; nó không thay thế phép tính.</p></article><article><b>Preview → Official Evidence</b><p>Preview là kết quả exploratory có thể hết hạn hoặc approximate. Promote sẽ revalidate và lưu result hash, context và provenance.</p></article><article><b>Traceability</b><p>Kết quả gắn với Dataset, Profile Run, QuerySpec/context và Workspace để Analyst biết nguồn và phạm vi của kết luận.</p></article><article><b>Human-in-the-loop</b><p>Analyst review proposal, kiểm tra visualization, review insight và quyết định nội dung report. AI hỗ trợ, không thay thế vai trò này.</p></article><article><b>Workspace isolation</b><p>Backend xác minh identity, membership và capability trên request được bảo vệ; frontend chỉ là lớp UX.</p></article></div><div className="pub-crosslink"><span>Muốn làm theo từng bước?</span><Link href="/guide">Đọc Guide từ kết nối đến PDF →</Link></div></div></section>
  </main><PublicFooter /></div>;
}
