"use client";

import Image from "next/image";
import Link from "next/link";
import { useRef } from "react";
import { PublicFooter } from "@/components/public-footer";
import { PublicMotion } from "@/components/public-motion";
import { PublicNavbar } from "@/components/public-navbar";
import { ProblemSolutionToggle } from "@/components/problem-solution-toggle";

const lifecycle = ["Kết nối / tải lên", "Profile", "Review", "Khám phá & trực quan hóa", "Insight", "Compare", "Report"];

export default function Home() {
  const motionRoot = useRef<HTMLElement>(null);
  return <div className="public-page"><PublicNavbar /><main ref={motionRoot} className="pub-home-main"><PublicMotion rootRef={motionRoot} />
    <section className="pub-section pub-hero-section"><div className="pub-container pub-hero"><div className="pub-hero-copy"><div className="pub-hero-kicker"><span className="pub-kicker-mark" aria-hidden="true">✦</span><span>DATA PROFILING / VDaAgent</span><span className="pub-kicker-code">EVIDENCE FIRST</span></div><h1>Hiểu dữ liệu.<br /><span>Phân tích có căn cứ.</span></h1><p className="pub-hero-lead">VDaAgent là workspace profiling và phân tích evidence-first dành cho Data Analyst: bắt đầu từ dataset chưa rõ, kiểm tra chất lượng, khám phá, trực quan hóa và đi đến insight có thể xem lại.</p><div className="pub-hero-actions"><Link href="/workspaces" className="pub-btn pub-btn-primary">Mở Workspace <span aria-hidden="true">→</span></Link><Link href="/guide" className="pub-btn pub-btn-ghost">Xem hướng dẫn <span aria-hidden="true">↗</span></Link></div><div className="pub-hero-proof"><span className="pub-proof-dot" aria-hidden="true" /><span>deterministic compute</span><span className="pub-proof-divider" aria-hidden="true" /><span>analyst review</span></div></div><div className="pub-hero-visual"><span className="pub-hero-orbit pub-hero-orbit-one" aria-hidden="true" /><span className="pub-hero-orbit pub-hero-orbit-two" aria-hidden="true" /><div className="pub-hero-panel"><div className="pub-hero-panel-bar"><span className="pub-panel-dot" aria-hidden="true" /><span>PROFILE RUN / CONTEXT</span><span className="pub-panel-status">READY TO REVIEW</span></div><Image className="pub-hero-dashboard-image" src="/img/home/home1.png" alt="Giao diện phân tích của VDaAgent" width={800} height={600} priority /></div><div className="pub-hero-sticker pub-hero-sticker-top"><span>WORKFLOW</span><strong>TRACEABLE</strong><small>from dataset to report</small></div><div className="pub-hero-sticker pub-hero-sticker-bottom"><span className="pub-sticker-spark" aria-hidden="true">✦</span><span>find the signal<br /><b>before the story</b></span></div><div className="pub-hero-mascot" aria-hidden="true"><div className="pub-mascot-crop"><Image src="/img/logo.png" alt="" width={110} height={110} unoptimized /></div></div></div></div></section>
    <section className="pub-section pub-features-section bg-surface"><div className="pub-container"><div className="pub-section-header"><div className="pub-section-index"><span>02</span><span>PROBLEM → SOLUTION</span></div><h2>Ít bước rời rạc hơn.<br /><em>Nhiều ngữ cảnh hơn.</em></h2><p>VDaAgent tập trung vào những kiểm tra và bằng chứng cần thiết để một Analyst có thể tiếp tục công việc một cách tự tin.</p></div><ProblemSolutionToggle /></div></section>
    <section className="pub-section"><div className="pub-container"><div className="pub-section-header"><div className="pub-section-index"><span>03</span><span>FULL LIFECYCLE</span></div><h2>Từ nguồn dữ liệu<br /><em>đến báo cáo.</em></h2><p>Mỗi bước đều có vai trò riêng trong workflow; Guide mô tả thao tác chi tiết theo UI hiện có.</p></div><ol className="pub-lifecycle">{lifecycle.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong>{index < lifecycle.length - 1 && <i aria-hidden="true">→</i>}</li>)}</ol><div className="pub-inline-actions"><Link href="/guide" className="pub-btn pub-btn-secondary">Mở hướng dẫn đầy đủ</Link><Link href="/about" className="pub-btn pub-btn-ghost">Tìm hiểu cách hệ thống hoạt động →</Link></div></div></section>
    <section className="pub-section bg-surface"><div className="pub-container"><div className="pub-section-header"><div className="pub-section-index"><span>04</span><span>PRINCIPLES</span></div><h2>Thiết kế để<br /><em>có thể kiểm chứng.</em></h2></div><div className="pub-principles-grid"><article><b>Evidence-first</b><p>Kết quả chính thức được lưu cùng ngữ cảnh và provenance.</p></article><article><b>Human-in-the-loop</b><p>Analyst review là một phần của workflow, không phải bước bị bỏ qua.</p></article><article><b>Deterministic compute</b><p>Số liệu phân tích đến từ engine tính toán có giới hạn rõ ràng.</p></article><article><b>Workspace-scoped</b><p>Dataset, Profile Run và kết quả được tổ chức trong Workspace.</p></article></div></div></section>
    <section className="pub-section pub-cta-section"><div className="pub-container"><div className="pub-cta-panel"><span className="pub-cta-sun" aria-hidden="true">✦</span><span className="pub-eyebrow">NEXT STEP</span><h2>Bắt đầu từ<br /><em>một dataset.</em></h2><p>Đi từ dữ liệu chưa rõ đến kết quả phân tích có ngữ cảnh, evidence và bước review của Analyst.</p><div className="pub-cta-actions"><Link href="/workspaces" className="pub-btn pub-btn-primary">Mở Workspace <span aria-hidden="true">→</span></Link><Link href="/docs" className="pub-btn pub-btn-secondary">Tra cứu thuật ngữ</Link></div></div></div></section>
  </main><PublicFooter /></div>;
}
