-- Canonical declarative source. Tenant and entity IDs are validated UUID strings by executable contracts.

CREATE TABLE organizations(org_id TEXT PRIMARY KEY,name TEXT NOT NULL,slow_moving_threshold_days INTEGER NOT NULL DEFAULT 90 CHECK(slow_moving_threshold_days>0));
CREATE TABLE organization_members(org_id TEXT NOT NULL REFERENCES organizations,user_id TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('owner','analyst','viewer')),PRIMARY KEY(org_id,user_id));
CREATE TABLE imports(org_id TEXT NOT NULL REFERENCES organizations,id TEXT NOT NULL,payload JSONB NOT NULL,file_hash TEXT NOT NULL,PRIMARY KEY(org_id,id),UNIQUE(org_id,file_hash));
CREATE TABLE snapshots(org_id TEXT NOT NULL,id TEXT NOT NULL,import_id TEXT NOT NULL,unit_external_id TEXT NOT NULL,snapshot_date DATE NOT NULL,project_external_id TEXT NOT NULL,zone_external_id TEXT NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),UNIQUE(org_id,unit_external_id,snapshot_date),FOREIGN KEY(org_id,import_id) REFERENCES imports(org_id,id));
CREATE INDEX snapshots_latest ON snapshots(org_id,unit_external_id,snapshot_date DESC);
CREATE TABLE conversations(org_id TEXT NOT NULL REFERENCES organizations,id TEXT NOT NULL,created_by TEXT NOT NULL,PRIMARY KEY(org_id,id));
CREATE TABLE runs(org_id TEXT NOT NULL REFERENCES organizations,id TEXT NOT NULL,created_by TEXT NOT NULL,idempotency_key TEXT NOT NULL,request_hash TEXT NOT NULL,status TEXT NOT NULL,lease_until TIMESTAMPTZ,worker_id TEXT,slow_moving_threshold_days INTEGER NOT NULL DEFAULT 90 CHECK(slow_moving_threshold_days>0),fencing_token INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),UNIQUE(org_id,created_by,idempotency_key));
CREATE INDEX runs_queue ON runs(status,lease_until,created_at);
CREATE TABLE run_snapshots(org_id TEXT NOT NULL,run_id TEXT NOT NULL,snapshot_id TEXT NOT NULL,PRIMARY KEY(org_id,run_id,snapshot_id),FOREIGN KEY(org_id,run_id) REFERENCES runs(org_id,id),FOREIGN KEY(org_id,snapshot_id) REFERENCES snapshots(org_id,id));
CREATE TABLE tasks(org_id TEXT NOT NULL,id TEXT NOT NULL,run_id TEXT NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),UNIQUE(org_id,run_id,id),FOREIGN KEY(org_id,run_id) REFERENCES runs(org_id,id));
CREATE TABLE artifacts(org_id TEXT NOT NULL,id TEXT NOT NULL,run_id TEXT NOT NULL,task_id TEXT NOT NULL,kind TEXT NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),UNIQUE(org_id,run_id,id),UNIQUE(org_id,run_id,kind),FOREIGN KEY(org_id,run_id,task_id) REFERENCES tasks(org_id,run_id,id));
CREATE TABLE artifact_inputs(org_id TEXT NOT NULL,run_id TEXT NOT NULL,artifact_id TEXT NOT NULL,input_id TEXT NOT NULL,PRIMARY KEY(org_id,artifact_id,input_id),FOREIGN KEY(org_id,run_id,artifact_id) REFERENCES artifacts(org_id,run_id,id),FOREIGN KEY(org_id,run_id,input_id) REFERENCES artifacts(org_id,run_id,id));
CREATE TABLE artifact_snapshots(org_id TEXT NOT NULL,run_id TEXT NOT NULL,artifact_id TEXT NOT NULL,snapshot_id TEXT NOT NULL,PRIMARY KEY(org_id,artifact_id,snapshot_id),FOREIGN KEY(org_id,run_id,artifact_id) REFERENCES artifacts(org_id,run_id,id),FOREIGN KEY(org_id,run_id,snapshot_id) REFERENCES run_snapshots(org_id,run_id,snapshot_id));
CREATE TABLE artifact_sources(org_id TEXT NOT NULL,artifact_id TEXT NOT NULL,import_id TEXT NOT NULL,PRIMARY KEY(org_id,artifact_id,import_id),FOREIGN KEY(org_id,artifact_id) REFERENCES artifacts(org_id,id),FOREIGN KEY(org_id,import_id) REFERENCES imports(org_id,id));
CREATE TABLE validations(org_id TEXT NOT NULL,id TEXT NOT NULL,run_id TEXT NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,run_id,id) REFERENCES artifacts(org_id,run_id,id));
CREATE TABLE events(org_id TEXT NOT NULL,id TEXT NOT NULL,run_id TEXT NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,run_id) REFERENCES runs(org_id,id));
CREATE TABLE messages(org_id TEXT NOT NULL,id TEXT NOT NULL,conversation_id TEXT NOT NULL,run_id TEXT NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,conversation_id) REFERENCES conversations(org_id,id),FOREIGN KEY(org_id,run_id) REFERENCES runs(org_id,id));
CREATE TABLE definitions(org_id TEXT NOT NULL REFERENCES organizations,id TEXT NOT NULL,created_by TEXT NOT NULL,next_run_at TIMESTAMPTZ NOT NULL,enabled INTEGER NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id));
CREATE TABLE occurrences(org_id TEXT NOT NULL,id TEXT NOT NULL,definition_id TEXT NOT NULL,scheduled_for TIMESTAMPTZ NOT NULL,run_id TEXT NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),UNIQUE(org_id,definition_id,scheduled_for),FOREIGN KEY(org_id,definition_id) REFERENCES definitions(org_id,id),FOREIGN KEY(org_id,run_id) REFERENCES runs(org_id,id));
CREATE TABLE reports(org_id TEXT NOT NULL,id TEXT NOT NULL,run_id TEXT NOT NULL,artifact_id TEXT NOT NULL,payload JSONB NOT NULL,PRIMARY KEY(org_id,id),UNIQUE(org_id,run_id),FOREIGN KEY(org_id,run_id,artifact_id) REFERENCES artifacts(org_id,run_id,id));
CREATE TABLE report_exports(org_id TEXT NOT NULL,report_id TEXT NOT NULL,format TEXT NOT NULL CHECK(format IN ('json','csv')),storage_path TEXT NOT NULL,content_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,PRIMARY KEY(org_id,report_id,format),FOREIGN KEY(org_id,report_id) REFERENCES reports(org_id,id));

ALTER TABLE snapshots ADD COLUMN list_price numeric GENERATED ALWAYS AS ((payload->>'list_price')::numeric) STORED;
ALTER TABLE snapshots ADD COLUMN area_sqm numeric GENERATED ALWAYS AS ((payload->>'area_sqm')::numeric) STORED;
ALTER TABLE snapshots ADD CONSTRAINT snapshots_payload_scope CHECK(payload->>'org_id'=org_id AND payload->>'snapshot_id'=id AND payload->>'import_id'=import_id);
ALTER TABLE artifacts ADD CONSTRAINT artifacts_payload_scope CHECK(payload->>'org_id'=org_id AND payload->>'artifact_id'=id AND payload->>'run_id'=run_id AND payload->>'task_id'=task_id);
ALTER TABLE runs ADD CONSTRAINT runs_payload_scope CHECK(payload->>'org_id'=org_id AND payload->>'run_id'=id AND payload->>'created_by'=created_by);
ALTER TABLE artifacts ADD CONSTRAINT artifact_hash_shape CHECK(payload->>'content_hash' ~ '^[a-f0-9]{64}$');
CREATE INDEX snapshots_import ON snapshots(org_id,import_id);
CREATE INDEX run_snapshots_source ON run_snapshots(org_id,snapshot_id);
CREATE INDEX tasks_run ON tasks(org_id,run_id);
CREATE INDEX artifact_inputs_input ON artifact_inputs(org_id,run_id,input_id);
CREATE INDEX artifact_snapshots_source ON artifact_snapshots(org_id,run_id,snapshot_id);
CREATE INDEX artifact_sources_source ON artifact_sources(org_id,import_id);
CREATE INDEX validations_run ON validations(org_id,run_id);
CREATE INDEX events_run ON events(org_id,run_id);
CREATE INDEX messages_conversation ON messages(org_id,conversation_id);
CREATE INDEX messages_run ON messages(org_id,run_id);
CREATE INDEX definitions_due ON definitions(enabled,next_run_at);
CREATE INDEX occurrences_run ON occurrences(org_id,run_id);
CREATE INDEX reports_artifact ON reports(org_id,run_id,artifact_id);
CREATE INDEX members_user ON organization_members(user_id,org_id);
CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC,anon,authenticated;
CREATE FUNCTION private.reject_immutable_change() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
BEGIN RAISE EXCEPTION 'immutable lineage record' USING ERRCODE='23514'; END;
$$;
REVOKE ALL ON FUNCTION private.reject_immutable_change() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER immutable_imports BEFORE UPDATE OR DELETE ON imports FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
CREATE TRIGGER immutable_snapshots BEFORE UPDATE OR DELETE ON snapshots FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
CREATE TRIGGER immutable_run_snapshots BEFORE UPDATE OR DELETE ON run_snapshots FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
CREATE TRIGGER immutable_artifacts BEFORE UPDATE OR DELETE ON artifacts FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
CREATE TRIGGER immutable_artifact_inputs BEFORE UPDATE OR DELETE ON artifact_inputs FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
CREATE TRIGGER immutable_artifact_snapshots BEFORE UPDATE OR DELETE ON artifact_snapshots FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
CREATE TRIGGER immutable_artifact_sources BEFORE UPDATE OR DELETE ON artifact_sources FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
CREATE TRIGGER immutable_occurrences BEFORE UPDATE OR DELETE ON occurrences FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
CREATE TRIGGER immutable_reports BEFORE UPDATE OR DELETE ON reports FOR EACH ROW EXECUTE FUNCTION private.reject_immutable_change();
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.organizations FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.organizations TO authenticated;
GRANT ALL ON public.organizations TO service_role;
CREATE POLICY workspace_read ON public.organizations FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=organizations.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.organization_members FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.organization_members TO authenticated;
GRANT ALL ON public.organization_members TO service_role;
CREATE POLICY workspace_read ON public.organization_members FOR SELECT TO authenticated USING (user_id=(SELECT auth.uid())::text);
ALTER TABLE public.imports ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.imports FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.imports TO authenticated;
GRANT ALL ON public.imports TO service_role;
CREATE POLICY workspace_read ON public.imports FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=imports.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.snapshots FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.snapshots TO authenticated;
GRANT ALL ON public.snapshots TO service_role;
CREATE POLICY workspace_read ON public.snapshots FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=snapshots.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.conversations FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.conversations TO authenticated;
GRANT ALL ON public.conversations TO service_role;
CREATE POLICY workspace_read ON public.conversations FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=conversations.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.runs FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.runs TO authenticated;
GRANT ALL ON public.runs TO service_role;
CREATE POLICY workspace_read ON public.runs FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=runs.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.run_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.run_snapshots FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.run_snapshots TO authenticated;
GRANT ALL ON public.run_snapshots TO service_role;
CREATE POLICY workspace_read ON public.run_snapshots FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=run_snapshots.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tasks FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.tasks TO authenticated;
GRANT ALL ON public.tasks TO service_role;
CREATE POLICY workspace_read ON public.tasks FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=tasks.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.artifacts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.artifacts FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.artifacts TO authenticated;
GRANT ALL ON public.artifacts TO service_role;
CREATE POLICY workspace_read ON public.artifacts FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=artifacts.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.artifact_inputs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.artifact_inputs FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.artifact_inputs TO authenticated;
GRANT ALL ON public.artifact_inputs TO service_role;
CREATE POLICY workspace_read ON public.artifact_inputs FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=artifact_inputs.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.artifact_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.artifact_snapshots FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.artifact_snapshots TO authenticated;
GRANT ALL ON public.artifact_snapshots TO service_role;
CREATE POLICY workspace_read ON public.artifact_snapshots FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=artifact_snapshots.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.artifact_sources ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.artifact_sources FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.artifact_sources TO authenticated;
GRANT ALL ON public.artifact_sources TO service_role;
CREATE POLICY workspace_read ON public.artifact_sources FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=artifact_sources.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.validations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.validations FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.validations TO authenticated;
GRANT ALL ON public.validations TO service_role;
CREATE POLICY workspace_read ON public.validations FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=validations.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.events FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.events TO authenticated;
GRANT ALL ON public.events TO service_role;
CREATE POLICY workspace_read ON public.events FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=events.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.messages FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.messages TO authenticated;
GRANT ALL ON public.messages TO service_role;
CREATE POLICY workspace_read ON public.messages FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=messages.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.definitions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.definitions FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.definitions TO authenticated;
GRANT ALL ON public.definitions TO service_role;
CREATE POLICY workspace_read ON public.definitions FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=definitions.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.occurrences ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.occurrences FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.occurrences TO authenticated;
GRANT ALL ON public.occurrences TO service_role;
CREATE POLICY workspace_read ON public.occurrences FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=occurrences.org_id AND m.user_id=(SELECT auth.uid())::text));
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.reports FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.reports TO authenticated;
GRANT ALL ON public.reports TO service_role;
CREATE POLICY workspace_read ON public.reports FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=reports.org_id AND m.user_id=(SELECT auth.uid())::text));

CREATE POLICY source_import_read ON storage.objects FOR SELECT TO authenticated USING (
 bucket_id='source-imports'
 AND EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=(storage.foldername(name))[1] AND m.user_id=(SELECT auth.uid())::text)
 AND EXISTS(SELECT 1 FROM public.imports i WHERE i.org_id=(storage.foldername(name))[1] AND i.payload->>'storage_path'=name)
);

ALTER TABLE public.report_exports ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.report_exports FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.report_exports TO authenticated;
GRANT ALL ON public.report_exports TO service_role;
CREATE POLICY workspace_read ON public.report_exports FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.organization_members m WHERE m.org_id=report_exports.org_id AND m.user_id=(SELECT auth.uid())::text));
-- Export objects are only delivered through short-lived BFF grants with membership revalidation.
