import Link from "next/link";
import { PublicFooter } from "@/components/public-footer";
import { PublicNavbar } from "@/components/public-navbar";

export const metadata = { title: "Guide · VDaAgent" };

const steps = [
  { id: "start", title: "Bắt đầu", body: <>Đăng nhập, chọn hoặc tạo <b>Workspace</b>, rồi mở các khu vực Dataset, Profile Run, Command Center, Compare và Reports. <b>Dataset</b> là nguồn dữ liệu; <b>Profile Run</b> là một phiên profiling gắn với dataset và là context trung tâm cho chart, Agent, compare và report.</> },
  { id: "drive", title: "Kết nối Google Drive", body: <>Trong luồng <b>Dataset mới</b>, nếu provider yêu cầu, chọn <b>Kết nối Google Drive</b>. Cho phép OAuth trong tab Google mới rồi quay lại tab upload; kết nối được scope theo Workspace và chỉ cần thực hiện một lần. Nếu popup bị chặn hoặc Workspace chưa bật provider, hãy cho phép popup/liên hệ quản trị viên. Drive là lớp lưu trữ/kết nối của luồng upload hiện có, không phải một màn hình query Google Drive riêng.</> },
  { id: "mongo", title: "Kết nối MongoDB Atlas", body: <>Từ Dataset mới, chọn <b>MongoDB Atlas</b> và tạo connection. Dán URI dạng <code>mongodb+srv://…</code> (dùng placeholder, không chia sẻ secret), nhập đúng database rồi bấm <b>Kiểm tra kết nối</b>. Sau khi kiểm tra thành công, chọn collection từ danh sách; nếu cần, nhập <b>Filter JSON</b> (mặc định <code>{"{}"}</code>) rồi kết nối. Credential được giữ ở backend; đặt tên dataset và tiếp tục profiling. Lỗi thường gặp là URI sai, IP allowlist, quyền database hoặc collection không tồn tại.</> },
  { id: "upload", title: "Tải lên dataset", body: <>Chọn <b>File từ máy</b>, kéo thả một hoặc nhiều file (hoặc thư mục) có đuôi <code>CSV</code>, <code>TSV</code>, <code>Parquet</code> hoặc <code>JSON</code>. Upload xong, nhập tên dataset. File không được hỗ trợ sẽ bị bỏ qua và UI báo rõ; không có bước làm sạch dữ liệu tự động trong luồng này.</> },
  { id: "profile", title: "Bắt đầu Profile Run", body: <>Chọn scan <b>full</b> hoặc <b>sample</b> (sample được đánh dấu approximate/uncertainty), sau đó bấm profiling. Hệ thống tạo Dataset → Profile Run → profiling job; job chạy bất đồng bộ qua worker. <b>Job status</b> có thể là queued, running, succeeded hoặc failed; <b>Profile Run status</b> có thể là created, pending_review, resuming, completed, failed hoặc cancelled. Mở Profile Run để theo dõi kết quả.</> },
  { id: "review", title: "Review proposals", body: <>Proposal là gợi ý metadata (candidate key, semantic type hoặc PII) do pipeline phát hiện. Khi có proposal pending, chọn <b>Xác nhận</b>, <b>Từ chối</b> hoặc <b>Chỉnh sửa phân loại</b>; chỉnh sửa cần giá trị chính thức và lý do. Mỗi proposal phải có quyết định, sau đó chọn <b>Lưu quyết định & tiếp tục</b>. Một số run không có proposal; khi đó UI báo không còn gì cần review và pipeline có thể hoàn tất.</> },
  { id: "explore", title: "Khám phá và trực quan hóa", body: <>Mở Profile Run đã <b>completed</b> trong Command Center, nhập câu hỏi phân tích và tạo/chọn plan. Chạy <b>Preview</b> để xem bảng/biểu đồ và limitations; preview là exploratory, không phải evidence bền vững. Kiểm tra cột, aggregation, filter, time grain và phạm vi rồi <b>Promote</b> kết quả phù hợp thành <b>Official Evidence</b>. Official được engine chạy lại, lưu context/result hash và có thể dùng cho Agent/report.</> },
  { id: "agent", title: "Tạo insight với Agent", body: <>Chọn đúng Profile Run trước khi hỏi. Agent dùng context và Official Evidence được cấp trong run; nó không đọc raw rows và không tự tính lại số liệu. Hãy hỏi cụ thể: “Biến nào liên quan nhất đến X?”, “Có khác biệt đáng kể giữa X và Y không?”, “Nhóm nào đóng góp nhiều nhất vào metric này?”, hoặc “Phân phối thay đổi thế nào so với Profile Run khác?”. Hãy xem insight như diễn giải cần Analyst review; correlation không chứng minh causation.</> },
  { id: "compare", title: "Compare Profile Runs", body: <>Vào <b>Compare</b>, cần ít nhất hai Profile Run đã completed. Chọn <b>Baseline</b> (mốc đối chiếu) và <b>Current</b> (phiên cần kiểm tra), rồi chạy so sánh. Kết quả là aggregate evidence theo cột, có signal và severity major/minor. Điều tra thay đổi về dữ liệu, scan mode và chất lượng trước khi kết luận; contract hiện tại không hiển thị raw rows hay phân phối bins chi tiết.</> },
  { id: "report", title: "Xây dựng Report Draft", body: <>Từ Official Evidence hoặc insight đã review, chọn <b>Ghim vào Báo cáo</b>. Trong report, sắp xếp item, sửa tiêu đề, thêm note và kiểm tra context/limitations. Draft còn chỉnh sửa được; khi nội dung ổn, chọn <b>Hoàn tất & Cập nhật</b> để tạo Snapshot bất biến.</> },
  { id: "export", title: "Preview và xuất PDF", body: <>Preview cho thấy report draft/snapshot sẽ được trình bày thế nào. Snapshot là trạng thái đóng băng ưu tiên cho chia sẻ và export; nếu chưa snapshot, UI có thể hiển thị draft theo quy định hiện tại. Tại trang report, chọn <b>Xuất báo cáo PDF</b> để tải file cuối. Kiểm tra tiêu đề, evidence, insight và limitations trước khi tải.</> },
];

export default function GuidePage() {
  return <div className="public-page"><PublicNavbar /><main className="pub-content"><section className="pub-section pub-page-hero"><div className="pub-container"><span className="pub-eyebrow">GUIDE / END TO END</span><h1>Từ dataset đầu tiên<br /><em>đến PDF cuối cùng.</em></h1><p className="pub-lead">Làm theo trình tự dưới đây trong Workspace. Khi gặp thuật ngữ hoặc metric, mở <Link href="/docs">Documentation</Link> để tra cứu.</p><nav className="pub-toc" aria-label="Mục lục Guide">{steps.map((step, index) => <a href={`#${step.id}`} key={step.id}><span>{String(index + 1).padStart(2, "0")}</span>{step.title}</a>)}</nav></div></section><section className="pub-section bg-surface"><div className="pub-container pub-guide-list">{steps.map((step, index) => <article className="pub-guide-step" id={step.id} key={step.id}><div className="pub-guide-number">{String(index + 1).padStart(2, "0")}</div><div><h2>{step.title}</h2><p>{step.body}</p></div></article>)}</div></section><section className="pub-section"><div className="pub-container"><div className="pub-section-header"><span className="pub-eyebrow">RECAP</span><h2>Một đường thẳng<br /><em>có thể kiểm chứng.</em></h2></div><div className="pub-recap">Kết nối / tải lên <b>→</b> Dataset <b>→</b> Profile Run <b>→</b> Review proposals <b>→</b> Explore <b>→</b> Visualize <b>→</b> Official Evidence <b>→</b> Agent Insight <b>→</b> Compare <b>→</b> Report Draft <b>→</b> Snapshot <b>→</b> Export PDF</div><div className="pub-inline-actions"><Link href="/docs" className="pub-btn pub-btn-secondary">Tra cứu metrics và status →</Link><Link href="/workspaces" className="pub-btn pub-btn-primary">Mở Workspace →</Link></div></div></section></main><PublicFooter /></div>;
}
