import {
  BarChart3,
  Database,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  Layers3,
  Server,
  Settings,
} from "lucide-react";

export const navItems = [
  ["dashboard", BarChart3, "Dashboard"],
  ["workspace", Database, "Data Workspace"],
  ["reports", BarChart3, "Reports"],
  ["tests", FlaskConical, "Statistical Tests"],
  ["settings", Settings, "Settings"],
];

export const sourceCards = [
  {
    id: "csv",
    icon: FileText,
    monogram: "CSV",
    category: "Files",
    title: "CSV files",
    provider: "Local file",
    description: "Single or multi-file upload, DuckDB profiling, relationship candidates.",
    status: "Ready",
    badge: "File",
  },
  {
    id: "excel",
    icon: FileSpreadsheet,
    monogram: "XL",
    category: "Files",
    title: "Excel workbook",
    provider: "Microsoft",
    description: "Profile each sheet as a source and infer relationships across sheets.",
    status: "Ready",
    badge: "Workbook",
  },
  {
    id: "azure_sql",
    icon: Server,
    monogram: "SQL",
    category: "Databases",
    title: "Azure SQL Database",
    provider: "Microsoft Azure",
    description: "Managed SQL Server-compatible database on Azure.",
    status: "Connector",
    badge: "Database",
    backendType: "sql_server",
    defaultPort: "1433",
    defaultDriver: "ODBC Driver 18 for SQL Server",
    hostPlaceholder: "server.database.windows.net",
  },
  {
    id: "azure_postgresql",
    icon: Database,
    monogram: "PG",
    category: "Databases",
    title: "Azure Database for PostgreSQL",
    provider: "Microsoft Azure",
    description: "Managed PostgreSQL service on Azure.",
    status: "Connector",
    badge: "Database",
    backendType: "postgresql",
    defaultPort: "5432",
    defaultDriver: "",
    hostPlaceholder: "server.postgres.database.azure.com",
  },
  {
    id: "bigquery",
    icon: BarChart3,
    monogram: "BQ",
    category: "Databases",
    title: "Google BigQuery",
    provider: "Google Cloud",
    description: "Serverless analytics warehouse using project, dataset, and service account auth.",
    status: "Needs adapter",
    badge: "Warehouse",
    backendType: null,
    hostPlaceholder: "project.dataset",
  },
  {
    id: "redshift",
    icon: Layers3,
    monogram: "RS",
    category: "Databases",
    title: "Amazon Redshift",
    provider: "AWS",
    description: "Cloud data warehouse with PostgreSQL-compatible wire protocol.",
    status: "Connector",
    badge: "Warehouse",
    backendType: "postgresql",
    defaultPort: "5439",
    defaultDriver: "",
    hostPlaceholder: "cluster.region.redshift.amazonaws.com",
  },
  {
    id: "snowflake",
    icon: Layers3,
    monogram: "SF",
    category: "Databases",
    title: "Snowflake",
    provider: "Snowflake",
    description: "Multi-cloud warehouse using account, warehouse, database, and role.",
    status: "Needs adapter",
    badge: "Warehouse",
    backendType: null,
    hostPlaceholder: "account.region.cloud",
  },
  {
    id: "databricks",
    icon: Layers3,
    monogram: "DBX",
    category: "Databases",
    title: "Databricks SQL Warehouse",
    provider: "Databricks",
    description: "Lakehouse SQL endpoint for Delta tables and Unity Catalog.",
    status: "Needs adapter",
    badge: "Lakehouse",
    backendType: null,
    hostPlaceholder: "workspace.cloud.databricks.com",
  },
  {
    id: "aws_rds_postgresql",
    icon: Database,
    monogram: "RDS",
    category: "Databases",
    title: "Amazon RDS PostgreSQL",
    provider: "AWS",
    description: "Managed PostgreSQL database on Amazon RDS.",
    status: "Connector",
    badge: "Database",
    backendType: "postgresql",
    defaultPort: "5432",
    defaultDriver: "",
    hostPlaceholder: "instance.region.rds.amazonaws.com",
  },
  {
    id: "aws_rds_mysql",
    icon: Database,
    monogram: "MY",
    category: "Databases",
    title: "Amazon RDS MySQL",
    provider: "AWS",
    description: "Managed MySQL database on Amazon RDS.",
    status: "Needs adapter",
    badge: "Database",
    backendType: null,
    defaultPort: "3306",
    hostPlaceholder: "instance.region.rds.amazonaws.com",
  },
  {
    id: "gcp_cloudsql_postgresql",
    icon: Database,
    monogram: "GPG",
    category: "Databases",
    title: "Cloud SQL PostgreSQL",
    provider: "Google Cloud",
    description: "Managed PostgreSQL database on Google Cloud SQL.",
    status: "Connector",
    badge: "Database",
    backendType: "postgresql",
    defaultPort: "5432",
    defaultDriver: "",
    hostPlaceholder: "public-ip-or-private-host",
  },
  {
    id: "fabric_warehouse",
    icon: Server,
    monogram: "FAB",
    category: "Databases",
    title: "Fabric Warehouse",
    provider: "Microsoft Fabric",
    description: "Warehouse or Lakehouse SQL endpoint using SQL Server-compatible access.",
    status: "Connector",
    badge: "Warehouse",
    backendType: "sql_server",
    defaultPort: "1433",
    defaultDriver: "ODBC Driver 18 for SQL Server",
    hostPlaceholder: "workspace.sql.azuresynapse.net",
  },
  {
    id: "parquet",
    icon: Layers3,
    monogram: "PQ",
    category: "Files",
    title: "Parquet",
    provider: "Columnar file",
    description: "Planned source for columnar file profiling.",
    status: "Planned",
    badge: "Lake",
    disabled: true,
  },
];

export const sectionOptions = ["schema", "columns", "correlations", "findings", "quality_summary"];

export const statisticalTests = [
  { id: "pearson-correlation", title: "Pearson correlation", description: "Linear association", fields: ["x_column", "y_column"] },
  { id: "spearman-correlation", title: "Spearman correlation", description: "Monotonic association", fields: ["x_column", "y_column"] },
  { id: "independent-t-test", title: "Independent t-test", description: "Compare two means", fields: ["value_column", "group_column"] },
  { id: "chi-square-independence", title: "Chi-square", description: "Categorical independence", fields: ["x_column", "y_column"] },
  { id: "one-way-anova", title: "One-way ANOVA", description: "Compare group means", fields: ["value_column", "group_column"] },
];
